# Generated by Django 5.0.3 on 2024-03-26 14:36

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampe',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Planification',
            fields=[
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('lampe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lampe')),
            ],
        ),
    ]
