# Generated by Django 5.0.3 on 2024-04-04 18:48

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_lampe_id_alter_noeud_id_alter_planification_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='planification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('not-completed', 'Not Completed')], default='not-completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='lampe',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='noeud',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='planification',
            name='id',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=22, primary_key=True, serialize=False),
        ),
    ]
